language: python

cache: pip

python:
  - "3.7"

install:
  - pip install poetry codecov
  - poetry install
  - pip install typer

script:
  - make lint test

after_success:
  - codecov

before_deploy:
  - cp README.md docs/
  - cp CHANGELOG.md docs/
  - make build docs

deploy:
  - provider: script
    script: poetry publish --no-interaction --username=$PYPI_USERNAME --password=$PYPI_PASSWORD
    skip_cleanup: true
    skip_existing: true
    on:
      branch: master
      tags: true

  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_ACCESS_TOKEN
    local-dir: site
    on:
      branch: master
